application: socialtank
version: 1
runtime: python
api_version: 1

handlers:
- url: /static_files
  static_dir: static_files
  
- url: /favicon.ico
  static_files: static_files/favicon.ico
  upload: static_files/favicon.ico
  
- url: /backup/.*
  script: main.py
  login: admin  
  
- url: .*
  script: main.py
